// Pool of "required words" the game can throw at the player.
// Organized by locale so each language gets its own evocative words.
// Keep entries lowercase — matching is case-insensitive but normalized to lowercase.

import type { Locale } from "@/lib/i18n/config"

// ---- English pool --------------------------------------------------------

const ENGLISH_WORDS: readonly string[] = [
  "adventure",
  "air",
  "alarm",
  "alley",
  "amber",
  "ambition",
  "anchor",
  "ancient",
  "angel",
  "animal",
  "antenna",
  "apple",
  "armor",
  "arrow",
  "ashes",
  "autumn",
  "backpack",
  "bamboo",
  "banner",
  "barrel",
  "basement",
  "basket",
  "battery",
  "beast",
  "beautiful",
  "bell",
  "bicycle",
  "bitter",
  "blanket",
  "blizzard",
  "bold",
  "brave",
  "breeze",
  "brick",
  "bright",
  "broken",
  "bronze",
  "bubble",
  "burning",
  "button",
  "cabin",
  "cactus",
  "calm",
  "camera",
  "candy",
  "captain",
  "carbon",
  "careful",
  "carnival",
  "carpet",
  "castle",
  "cave",
  "ceremony",
  "chain",
  "chalk",
  "champion",
  "chapter",
  "cherry",
  "circle",
  "clay",
  "clean",
  "clear",
  "cliff",
  "cloudy",
  "clover",
  "coal",
  "coast",
  "coffee",
  "cold",
  "colony",
  "column",
  "comet",
  "compass",
  "concert",
  "concrete",
  "copper",
  "coral",
  "cotton",
  "courage",
  "cradle",
  "crater",
  "crow",
  "crown",
  "crystal",
  "cube",
  "curious",
  "current",
  "curtain",
  "danger",
  "dawn",
  "delicate",
  "desert",
  "diamond",
  "dimension",
  "dinosaur",
  "distant",
  "doctor",
  "double",
  "dragon",
  "drawer",
  "drought",
  "dust",
  "eagle",
  "earth",
  "echo",
  "eclipse",
  "edge",
  "electric",
  "elegant",
  "element",
  "emerald",
  "emotion",
  "empire",
  "enormous",
  "eternal",
  "exact",
  "expert",
  "explorer",
  "factory",
  "familiar",
  "fantastic",
  "farm",
  "fast",
  "feather",
  "festival",
  "fire",
  "flame",
  "flash",
  "flat",
  "flexible",
  "flour",
  "flower",
  "foggy",
  "forbidden",
  "forest",
  "formal",
  "fortune",
  "fountain",
  "freedom",
  "fresh",
  "frozen",
  "furious",
  "galaxy",
  "garden",
  "garlic",
  "gate",
  "general",
  "generous",
  "gentle",
  "ghost",
  "glacier",
  "global",
  "golden",
  "grass",
  "grateful",
  "gravity",
  "guardian",
  "guitar",
  "hammer",
  "harvest",
  "hawk",
  "heavy",
  "helmet",
  "hidden",
  "hollow",
  "honest",
  "honey",
  "horizon",
  "humid",
  "ideal",
  "illusion",
  "impossible",
  "infinite",
  "innocent",
  "instant",
  "island",
  "ivory",
  "jasmine",
  "jewel",
  "jungle",
  "kingdom",
  "lagoon",
  "language",
  "lantern",
  "large",
  "lavender",
  "leaf",
  "legend",
  "lemon",
  "letter",
  "lighthouse",
  "limit",
  "liquid",
  "machine",
  "magnet",
  "mansion",
  "marble",
  "market",
  "meadow",
  "medal",
  "melody",
  "midnight",
  "mineral",
  "mint",
  "mirror",
  "modern",
  "monument",
  "moon",
  "motor",
  "mountain",
  "narrow",
  "natural",
  "needle",
  "neon",
  "nervous",
  "noble",
  "nomad",
  "notebook",
  "novel",
  "oak",
  "oasis",
  "ocean",
  "office",
  "orange",
  "organic",
  "oven",
  "owl",
  "palace",
  "palm",
  "panther",
  "patient",
  "peaceful",
  "pearl",
  "pepper",
  "permanent",
  "piano",
  "pine",
  "planet",
  "polar",
  "porcelain",
  "port",
  "precious",
  "private",
  "promise",
  "proud",
  "public",
  "pure",
  "rabbit",
  "radiant",
  "rainbow",
  "rare",
  "ribbon",
  "river",
  "robust",
  "safe",
  "sand",
  "shadow",
  "sharp",
  "silver",
  "simple",
  "soft",
  "soldier",
  "steel",
  "storm",
  "strange",
  "stream",
  "strong",
  "sunrise",
  "thunder",
  "tiger",
  "tower",
  "treasure",
  "velvet",
  "volcano",
  "water",
  "whisper",
  "wild",
  "winter",
  "wolf",
  "wooden",
] as const

// ---- Spanish pool --------------------------------------------------------

const SPANISH_WORDS: readonly string[] = [
  "acero",
  "agua",
  "águila",
  "aire",
  "alarma",
  "alegre",
  "alfombra",
  "algodón",
  "almendra",
  "ámbar",
  "ambición",
  "ángel",
  "animal",
  "antena",
  "antiguo",
  "arcoíris",
  "arena",
  "armadura",
  "arroyo",
  "aventura",
  "balcón",
  "bambú",
  "bandera",
  "barril",
  "batería",
  "bestia",
  "bicicleta",
  "bosque",
  "botón",
  "brillante",
  "brisa",
  "bronce",
  "brújula",
  "burbuja",
  "cabaña",
  "cactus",
  "cadena",
  "café",
  "calma",
  "cámara",
  "campana",
  "campeón",
  "canal",
  "cañón",
  "capitán",
  "capítulo",
  "caramelo",
  "carbón",
  "carnaval",
  "carro",
  "carta",
  "casco",
  "castillo",
  "catedral",
  "caverna",
  "cemento",
  "ceniza",
  "ceremonia",
  "cereza",
  "chimenea",
  "cinta",
  "círculo",
  "claro",
  "cobre",
  "colonia",
  "columna",
  "cometa",
  "compañero",
  "concierto",
  "coral",
  "corona",
  "corriente",
  "cortina",
  "cosecha",
  "cristal",
  "cuaderno",
  "cubo",
  "cuervo",
  "cuna",
  "curioso",
  "delicado",
  "desierto",
  "diamante",
  "dimensión",
  "dinosaurio",
  "distante",
  "doble",
  "dorado",
  "dragón",
  "eclipse",
  "eco",
  "eléctrico",
  "elegante",
  "elemento",
  "emoción",
  "emperador",
  "enorme",
  "entrada",
  "escalera",
  "esmeralda",
  "espejo",
  "estrella",
  "eterno",
  "exacto",
  "experto",
  "explorador",
  "extraño",
  "familiar",
  "fantasma",
  "fantástico",
  "faro",
  "feroz",
  "festival",
  "flecha",
  "flexible",
  "fogata",
  "formal",
  "fortuna",
  "frágil",
  "fresco",
  "frío",
  "fuego",
  "fuente",
  "furioso",
  "galaxia",
  "general",
  "generoso",
  "glaciar",
  "global",
  "grande",
  "granito",
  "gravedad",
  "guardián",
  "guitarra",
  "hermoso",
  "hierba",
  "hogar",
  "hoja",
  "honesto",
  "horizonte",
  "horno",
  "húmedo",
  "ideal",
  "ilusión",
  "imperio",
  "imposible",
  "infinito",
  "inmenso",
  "inocente",
  "invierno",
  "isla",
  "jardín",
  "jazmín",
  "joya",
  "ladrillo",
  "laguna",
  "leyenda",
  "libertad",
  "limón",
  "limpio",
  "líquido",
  "llama",
  "lobo",
  "luna",
  "madera",
  "mansión",
  "manzana",
  "máquina",
  "mármol",
  "martillo",
  "medalla",
  "medianoche",
  "melodía",
  "menta",
  "mercado",
  "miel",
  "mineral",
  "moderno",
  "montaña",
  "monumento",
  "motor",
  "natural",
  "nervioso",
  "noble",
  "novela",
  "nublado",
  "océano",
  "oficina",
  "orgánico",
  "orgulloso",
  "otoño",
  "paciente",
  "palacio",
  "palmera",
  "pantera",
  "peligro",
  "perla",
  "permanente",
  "pesado",
  "piano",
  "pimienta",
  "pino",
  "planeta",
  "plata",
  "pluma",
  "polar",
  "polvo",
  "porcelana",
  "precioso",
  "privado",
  "promesa",
  "público",
  "puerta",
  "puerto",
  "puro",
  "radiante",
  "rápido",
  "raro",
  "rebelde",
  "reino",
  "relámpago",
  "río",
  "roble",
  "roto",
  "salvaje",
  "seguro",
  "selva",
  "sencillo",
  "sequía",
  "soldado",
  "sombra",
  "suave",
  "susurro",
  "terciopelo",
  "tesoro",
  "tierra",
  "tigre",
  "tormenta",
  "torre",
  "tranquilo",
  "trébol",
  "trueno",
  "valiente",
  "ventisca",
  "volcán",
] as const

// ---- Locale → pool map ---------------------------------------------------

const WORD_POOLS: Record<string, readonly string[]> = {
  en: ENGLISH_WORDS,
  es: SPANISH_WORDS,
}

/**
 * Get the word pool for a given locale.
 * Falls back to English (and logs a warning) if the locale is unknown.
 */
export function getWordPool(locale: Locale): readonly string[] {
  const pool = WORD_POOLS[locale]
  if (pool) return pool
  console.warn(
    `[words] No word pool for locale "${locale}". Falling back to English.`,
  )
  return ENGLISH_WORDS
}

/**
 * Pick a random word from the pool, avoiding any words in `exclude`.
 * Falls back to picking from the full pool if `exclude` covers everything.
 *
 * If `poolOverride` is provided and non-empty, it is used as the source.
 * Otherwise we use the hardcoded pool for the given locale. This is how the
 * "custom categories" feature swaps in a backend-generated word list.
 */
export function pickRequiredWord(
  locale: Locale,
  exclude: ReadonlySet<string> = new Set(),
  poolOverride?: readonly string[],
): string {
  const pool =
    poolOverride && poolOverride.length > 0 ? poolOverride : getWordPool(locale)
  const available = pool.filter((w) => !exclude.has(normalizeForMatch(w)))
  const source = available.length > 0 ? available : pool
  return source[Math.floor(Math.random() * source.length)]
}

// ---- Diacritics-insensitive matching helpers ------------------------------

// Letters that don't decompose under NFD but that humans routinely type as
// their plainer ASCII counterparts (stroked letters, ligatures, special
// pairs). Mapped here so `normalizeForMatch` treats e.g. "łaska" and "laska",
// "Straße" and "strasse", "œuvre" and "oeuvre" as equivalent.
//
// Keys are lowercase only; the `.toLowerCase()` step folds uppercase forms
// before this map is applied.
const SPECIAL_LETTER_MAP: Record<string, string> = {
  "ł": "l",
  "ø": "o",
  "đ": "d",
  "ð": "d",
  "þ": "th",
  "ß": "ss",
  "æ": "ae",
  "œ": "oe",
  "ı": "i",
  "ħ": "h",
  "ŧ": "t",
  "ƀ": "b",
}

const SPECIAL_LETTER_RE = new RegExp(
  `[${Object.keys(SPECIAL_LETTER_MAP).join("")}]`,
  "g",
)

/**
 * Normalize a string for diacritic- and special-letter-insensitive matching.
 *
 * Steps, in order:
 * 1. Lowercase, so the special-letter map only needs lowercase keys.
 * 2. Replace stroked / ligature letters that don't decompose under NFD
 *    (ł, ø, ß, æ, …) with their close ASCII equivalents — these are
 *    "letters that are too special and people most often type the closest
 *    plain letter instead".
 * 3. NFD-decompose, then strip the combining-mark range U+0300–U+036F so
 *    accented letters (á, ñ, ç, ü, …) collapse onto their base letter.
 *
 * E.g. "brújula" → "brujula", "Straße" → "strasse", "façade" → "facade".
 */
export function normalizeForMatch(text: string): string {
  return text
    .toLowerCase()
    .replace(SPECIAL_LETTER_RE, (c) => SPECIAL_LETTER_MAP[c] ?? c)
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
}

/**
 * Check whether `candidate` matches `required` in a diacritics-insensitive,
 * case-insensitive manner, also ignoring surrounding punctuation.
 *
 * E.g. matchesWord("brújula", "brujula") → true
 *      matchesWord("¡Mármol!", "marmol") → true
 */
export function matchesWord(candidate: string, required: string): boolean {
  // Strip leading/trailing punctuation from candidate
  const stripped = candidate.replace(/^[\p{P}\p{S}]+|[\p{P}\p{S}]+$/gu, "")
  return normalizeForMatch(stripped) === normalizeForMatch(required)
}
